In [1]:
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
import pandas as pd

In [3]:
#dataset --> https://www.kaggle.com/datasets/yasserh/housing-prices-dataset
data = pd.read_csv("../DataSet/pre_processed_data.csv")

In [4]:
data.head()

Unnamed: 0  age     bmi  children      charges  sex_male  smoker_yes
0           0   19  27.900         0  16884.92400     False        True
1           1   18  33.770         1   1725.55230      True       False
2           2   28  33.000         3   4449.46200      True       False
3           3   33  22.705         0  21984.47061      True       False
4           4   32  28.880         0   3866.85520      True       False

In [5]:
x = data.loc[ : , ["age", "bmi", "children", "sex_male", "smoker_yes"] ]

In [6]:
x.head()

age     bmi  children  sex_male  smoker_yes
0   19  27.900         0     False        True
1   18  33.770         1      True       False
2   28  33.000         3      True       False
3   33  22.705         0      True       False
4   32  28.880         0      True       False

In [7]:
y = data.loc[: , ["charges"]]

In [8]:
y.head()

charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

# Normalization

In [13]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()

In [14]:
xdata = sc_x.fit_transform(x)
ydata = sc_y.fit_transform(y.values.reshape(-1, 1)).ravel()

In [15]:
xdata, ydata

(array([[-1.44041773, -0.45315959, -0.90923416, -1.00977099,  1.96966039],
        [-1.51164747,  0.50942165, -0.07944162,  0.99032355, -0.50770174],
        [-0.79935006,  0.3831546 ,  1.58014347,  0.99032355, -0.50770174],
        ...,
        [-1.51164747,  1.01448983, -0.90923416, -1.00977099, -0.50770174],
        [-1.29795825, -0.79752426, -0.90923416, -1.00977099, -0.50770174],
        [ 1.55123139, -0.26129928, -0.90923416, -1.00977099,  1.96966039]]),
 array([ 0.2978567 , -0.9543806 , -0.72937251, ..., -0.96228744,
        -0.9310536 ,  1.31029752]))

In [16]:
x_train, x_test, y_train, y_test = train_test_split(xdata, ydata, random_state=0) # herea random state help to give same result of split when ever run the code

# Train a Model

In [133]:
model = SVR(kernel="rbf", C=10)

In [134]:
model.fit(x_train, y_train)

SVR(C=10)

In [135]:
model.intercept_

array([0.52510582])

In [136]:
model.support_

array([  2,   8,   9,  10,  11,  16,  17,  19,  22,  28,  29,  38,  40,
        42,  44,  51,  56,  58,  60,  67,  68,  74,  78,  79,  81,  87,
        88,  91,  92,  93,  95, 100, 101, 102, 103, 105, 111, 112, 115,
       117, 120, 126, 149, 150, 158, 159, 164, 172, 182, 183, 184, 185,
       187, 190, 194, 195, 203, 210, 215, 219, 220, 231, 232, 233, 236,
       237, 241, 243, 245, 251, 258, 259, 264, 265, 266, 269, 270, 272,
       273, 277, 278, 281, 286, 290, 292, 293, 295, 299, 300, 302, 303,
       304, 305, 309, 310, 313, 314, 317, 319, 321, 325, 328, 329, 330,
       332, 333, 335, 340, 342, 347, 351, 352, 356, 357, 359, 361, 362,
       370, 377, 385, 387, 397, 400, 402, 403, 409, 411, 413, 415, 416,
       420, 425, 427, 428, 429, 430, 431, 432, 435, 436, 442, 446, 448,
       452, 454, 456, 458, 461, 463, 465, 467, 475, 476, 478, 484, 485,
       487, 489, 493, 494, 495, 496, 501, 507, 508, 511, 512, 513, 518,
       519, 520, 521, 522, 524, 525, 528, 529, 533, 534, 536, 53

In [137]:
y_pred = model.predict(x_test)

In [138]:
from sklearn.metrics import r2_score

In [139]:
r2_score(y_test, y_pred)

0.8443631416258697

# Export model

In [140]:
import joblib

In [141]:
joblib.dump(model, "svr.joblib")

['svr.joblib']

# Load model and predict

In [142]:
loadedmodel = joblib.load("svr.joblib")

In [143]:
inputData = sc_x.transform([[25, 34, 0, True, False]])

/home/krishna/anaconda3/envs/pytorchEnv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [147]:
res = loadedmodel.predict(inputData)
res

array([-0.81989968])

In [148]:
sc_y.inverse_transform([[-0.81989968]])

array([[3353.55544284]])